apiVersion: v2
name: hostpath-csi-driver
version: 1.4.0
appVersion: 1.4.0
home: https://github.com/platform9/helm-charts
description: Hostpath CSI Driver. Certified on BareOS, AWS, Azure, AKS, GKS
keywords:
  - Certified certified-on-all Non-Production-Only
sources:
  - https://github.com/platform9/helm-charts
type: application
kubeVersion: ">=1.20.0-0"
