apiVersion: v2
name: fluentd-elasticsearch
description: A Helm chart for Kubernetes. Certified on BareOS ,AWS ,Azure ,AKS ,GKS
keywords:
 - Certified certified-on-all Non-Production-Only
# type: application
version: 0.2.6
appVersion: v1.12.0
icon: https://coralogix.com/wp-content/uploads/2020/04/fluentd-guide-700x430.png
home: https://www.fluentd.org/
sources:
  - https://github.com/fluent/fluentd/
  - https://github.com/fluent/fluentd-kubernetes-daemonset
