apiVersion: v2
name: ingress-nginx-with-lb
version: 3.30.0
appVersion: 0.46.0
home: https://github.com/platform9/helm-charts
description: Ingress controller for Kubernetes using NGINX as a reverse proxy(External load balancer present). Certified on BareOS without MetalLB, AWS, Azure, AKS, GKS
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
keywords:
  - ingress
  - nginx
  - Certified certified-on-BareOS-AWS-Azure-GKS Non-Production-Only
sources:
  - https://github.com/platform9/helm-charts
type: application
kubeVersion: ">=1.16.0-0"
